### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by praharshbhatt** [tiamo/flutter-concentric-transition#5]
```
I/flutter ( 9578): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9578): The following _CastError was thrown building AnimatedBuilder(animation: PageController#5a88a(one
I/flutter ( 9578): client, offset 0.0), dirty, state: _AnimatedState#c220a):
I/flutter ( 9578): Null check operator used on a null value
I/flutter ( 9578): 
I/flutter ( 9578): The relevant error-causing widget was:
I/flutter ( 9578):   AnimatedBuilder
I/flutter ( 9578):   file:///home/praharsh/.pub-cache/hosted/pub.dartlang.org/concentric_transition-0.1.1/lib/page_view.dart:122:20
I/flutter ( 9578): 
I/flutter ( 9578): When the exception was thrown, this was the stack:
I/flutter ( 9578): #0      ScrollPosition.minScrollExtent (package:flutter/src/widgets/scroll_position.dart:136:49)
I/flutter ( 9578): #1      _ConcentricPageViewState.build.<anonymous closure>.<anonymous closure> (package:concentric_transition/page_view.dart:127:48)
I/flutter ( 9578): #2      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1466:19)
I/flutter ( 9578): #3      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:174:48)
I/flutter ( 9578): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
I/flutter ( 9578): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
I/flutter ( 9578): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
I/flutter ( 9578): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
I/flutter ( 9578): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4474:5)
I/flutter ( 9578): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4658:11)
I/flutter ( 9578): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
I/flutter ( 9578): ...     Normal element mounting (33 frames)
I/flutter ( 9578): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
I/flutter ( 9578): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
I/flutter ( 9578): #45     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1229:37)
I/flutter ( 9578): #46     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1214:20)
I/flutter ( 9578): #47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
I/flutter ( 9578): #48     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1207:12)
I/flutter ( 9578): #49     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
I/flutter ( 9578): #50     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1894:59)
I/flutter ( 9578): #51     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter ( 9578): #52     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1894:14)
I/flutter ( 9578): #53     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
I/flutter ( 9578): #54     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:422:5)
I/flutter ( 9578): #55     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:205:12)
I/flutter ( 9578): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #57     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
I/flutter ( 9578): #58     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
I/flutter ( 9578): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #60     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:512:13)
I/flutter ( 9578): #61     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1570:12)
I/flutter ( 9578): #62     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1479:20)
I/flutter ( 9578): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #79     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:546:11)
I/flutter ( 9578): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #83     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:54:11)
I/flutter ( 9578): #84     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:570:43)
I/flutter ( 9578): #85     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:597:12)
I/flutter ( 9578): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #90     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1371:11)
I/flutter ( 9578): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #107    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3362:13)
I/flutter ( 9578): #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #111    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
I/flutter ( 9578): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:118:14)
I/flutter ( 9578): #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1784:7)
I/flutter ( 9578): #123    RenderView.performLayout (package:flutter/src/rendering/view.dart:153:14)
I/flutter ( 9578): #124    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1641:7)
I/flutter ( 9578): #125    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter ( 9578): #126    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:453:19)
I/flutter ( 9578): #127    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
I/flutter ( 9578): #128    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
I/flutter ( 9578): #129    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
I/flutter ( 9578): #130    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter ( 9578): #131    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
I/flutter ( 9578): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter ( 9578): 
I/flutter ( 9578): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9578): Firebase Token: c6yawLOLSuK4r65oBBNeSG:APA91bHDwlUyo2aBoaWItWfa__uwVJhJRBmd6YnR0SfNovKtsJg2SvNmutwLQI4w47PbIB5aF5Zr3OJVcRxQSPigJCGRo9d1PRQ33_e7jyOuu-c1Kdq2yfD3NOaJSumVkuG5DLUC6ITm

```

**Comment by tiamo** [comment]
Hi @praharshbhatt, 
Do you use flutter with null-safety enabled ?
Which version of flutter?

**Comment by praharshchargelab** [comment]
Yes, I do have null safety enabled.
This only happens in the newer flutter 2.0.

**Comment by richardracz** [comment]
#6
Hi, I made a pull request to fix this issue. Let me know if it works on your part.

**Comment by dalton5** [comment]
How can I get the version with the fix pleasE?

**Comment by tiamo** [comment]
added v1.0.0 with null-safety support.
